[project]
name = "mire"
version = "0.0.1"
description = "Library for the Mire language"
entry = "code/mod.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0

[paths]
sources = "."
tests = "tests"
output = "bin"
cache = "bin/.cache"

[exports]
vec = "core/vec"
map = "core/map"
str = "core/str"
maybe = "core/maybe"
result = "core/result"
arr = "core/arr"
io = "core/io"
math = "core/math"
